-- 修复逻辑删除问题：为所有表添加 deleted 字段
-- MyBatis-Plus 全局配置了逻辑删除，需要每个表有 deleted 字段
-- 0 表示未删除，1 表示已删除

ALTER TABLE lg_user ADD COLUMN deleted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE lg_project ADD COLUMN deleted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE lg_source ADD COLUMN deleted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE lg_database_connection ADD COLUMN deleted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE lg_table_metadata ADD COLUMN deleted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE lg_test_case ADD COLUMN deleted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE lg_test_batch ADD COLUMN deleted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE lg_test_result ADD COLUMN deleted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE lg_entity_relationship ADD COLUMN deleted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE lg_code_entity ADD COLUMN deleted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE lg_embedding_cache ADD COLUMN deleted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE lg_report ADD COLUMN deleted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE lg_ai_chat_session ADD COLUMN deleted SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE lg_ai_chat_message ADD COLUMN deleted SMALLINT NOT NULL DEFAULT 0;
