package io.github.legacygraph;

import com.openai.client.OpenAIClientImpl;
import com.openai.core.ClientOptions;
import org.springframework.ai.openai.OpenAiEmbeddingModel;
import org.springframework.ai.openai.OpenAiEmbeddingOptions;
import org.springframework.ai.openai.http.okhttp.SpringAiOpenAiHttpClient;

import java.sql.*;

/**
 * 独立测试：不依赖 Spring 容器，直接验证向量化写入 lg_vector_document
 * 需要 Ollama bge-m3 在 localhost:11434 运行
 * 需要 PostgreSQL 在 118.145.225.100:5432
 */
public class VectorDocumentQuickTest {
    public static void main(String[] args) throws Exception {
        String jdbcUrl = "jdbc:postgresql://118.145.225.100:5432/legacy_graph";
        String dbUser = "mumuai";
        String dbPass = "Liucl157";

        // 1. 确保 V23 迁移已执行（表结构正确）
        try (Connection conn = DriverManager.getConnection(jdbcUrl, dbUser, dbPass)) {
            // 检查表结构
            DatabaseMetaData meta = conn.getMetaData();
            ResultSet cols = meta.getColumns(null, null, "lg_vector_document", null);
            System.out.println("📋 lg_vector_document 列:");
            while (cols.next()) {
                System.out.println("  " + cols.getString("COLUMN_NAME")
                        + " " + cols.getString("TYPE_NAME")
                        + "(" + cols.getInt("COLUMN_SIZE") + ")");
            }
            cols.close();

            // 手动执行 V23（幂等）
            try (Statement stmt = conn.createStatement()) {
                // 先删旧表（如果有 BIGINT project_id）
                stmt.execute("DROP TABLE IF EXISTS lg_vector_document");
                stmt.execute("""
                    CREATE TABLE IF NOT EXISTS lg_vector_document (
                        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        project_id      VARCHAR(64) NOT NULL,
                        version_id      VARCHAR(64) NOT NULL,
                        chunk_type      VARCHAR(64) NOT NULL DEFAULT 'DOC',
                        source_uri      TEXT,
                        source_hash     VARCHAR(128),
                        chunk_index     INT,
                        content         TEXT NOT NULL,
                        content_sha256  VARCHAR(128),
                        meta            JSONB DEFAULT '{}'::JSONB,
                        embedding       vector(1024),
                        embedding_model VARCHAR(128),
                        embedding_dim   INT,
                        created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
                System.out.println("✅ 表结构已就绪");
            }
        }

        // 2. 创建 Ollama EmbeddingModel
        var httpClient = SpringAiOpenAiHttpClient.builder()
                .timeout(java.time.Duration.ofSeconds(60))
                .build();
        var clientOptions = ClientOptions.builder()
                .baseUrl("http://localhost:11434/v1")
                .apiKey("ollama")
                .httpClient(httpClient)
                .build();
        var client = new OpenAIClientImpl(clientOptions);
        var options = OpenAiEmbeddingOptions.builder()
                .model("bge-m3")
                .apiKey("ollama")
                .baseUrl("http://localhost:11434/v1")
                .build();
        OpenAiEmbeddingModel embeddingModel = OpenAiEmbeddingModel.builder()
                .openAiClient(client)
                .options(options)
                .build();

        System.out.println("✅ EmbeddingModel 已创建: bge-m3 @ localhost:11434");

        // 3. 向量化测试
        String testProjectId = "test-vec-quick";
        String testVersionId = "v1";
        String content = """
                LegacyGraph 是一个代码知识图谱平台，核心功能包括：
                1. 代码扫描与结构抽取
                2. 数据库元数据分析
                3. 文档 AI 理解
                4. 业务图谱构建
                5. 语义向量检索
                本系统采用 Spring Boot + MyBatis-Plus + Neo4j + pgvector 技术栈。
                """;

        float[] embedding = embeddingModel.embed(content);
        System.out.println("✅ 向量化成功: dim=" + embedding.length);

        // 4. 写入数据库
        String insertSql = """
                INSERT INTO lg_vector_document
                (project_id, version_id, chunk_type, source_uri, source_hash,
                 chunk_index, content, content_sha256, meta,
                 embedding, embedding_model, embedding_dim, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?::JSONB, ?::vector, ?, ?, NOW())
                """;

        try (Connection conn = DriverManager.getConnection(jdbcUrl, dbUser, dbPass);
             PreparedStatement ps = conn.prepareStatement(insertSql, Statement.RETURN_GENERATED_KEYS)) {

            String contentSha256 = sha256(content);
            String sourceHash = sha256("/test/readme.md" + 0);
            String embeddingStr = floatArrayToPgVector(embedding);

            ps.setString(1, testProjectId);
            ps.setString(2, testVersionId);
            ps.setString(3, "DOC");
            ps.setString(4, "/test/readme.md");
            ps.setString(5, sourceHash);
            ps.setInt(6, 0);
            ps.setString(7, content);
            ps.setString(8, contentSha256);
            ps.setString(9, "{}");
            ps.setString(10, embeddingStr);
            ps.setString(11, "bge-m3");
            ps.setInt(12, embedding.length);

            int rows = ps.executeUpdate();
            ResultSet keys = ps.getGeneratedKeys();
            long id = keys.next() ? keys.getLong(1) : -1;

            System.out.println("✅ 写入成功: id=" + id + " rows=" + rows);
        }

        // 5. 验证读取
        try (Connection conn = DriverManager.getConnection(jdbcUrl, dbUser, dbPass);
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT id, project_id, version_id, chunk_type, source_uri, embedding_dim " +
                     "FROM lg_vector_document WHERE project_id = ?")) {
            ps.setString(1, testProjectId);
            ResultSet rs = ps.executeQuery();
            int count = 0;
            while (rs.next()) {
                count++;
                System.out.println("📄 [" + rs.getLong("id") + "] "
                        + rs.getString("chunk_type") + " | "
                        + rs.getString("source_uri") + " | "
                        + "dim=" + rs.getInt("embedding_dim"));
            }
            System.out.println("✅ 查询结果: " + count + " 条记录");

            // 6. 清理
            try (Statement stmt = conn.createStatement()) {
                int deleted = stmt.executeUpdate("DELETE FROM lg_vector_document WHERE project_id = '" + testProjectId + "'");
                System.out.println("🧹 清理完成: 删除 " + deleted + " 条");
            }
        }

        System.out.println("\n🎉 全部验证通过！向量化写入 lg_vector_document 链路正常。");
    }

    private static String sha256(String input) {
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("SHA-256");
            byte[] hash = md.digest(input.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder();
            for (byte b : hash) sb.append(String.format("%02x", b));
            return sb.toString();
        } catch (Exception e) {
            return Integer.toHexString(input.hashCode());
        }
    }

    private static String floatArrayToPgVector(float[] arr) {
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < arr.length; i++) {
            if (i > 0) sb.append(",");
            sb.append(arr[i]);
        }
        sb.append("]");
        return sb.toString();
    }
}
