-- ============================================
-- V23: 修复 lg_vector_document 表结构
-- ============================================
-- 原表 project_id 为 BIGINT，但项目ID实际为 UUID 字符串
-- 缺少 version_id 列和 pgvector embedding 列
-- 表为空时可安全重建
-- pgvector 扩展可能未安装，embedding 先以 TEXT 建列，再尝试转换

-- 删除旧表（空表，无数据损失）
DROP TABLE IF EXISTS lg_vector_document;

-- 重建：正确的列类型（embedding 先以 TEXT 建列）
CREATE TABLE IF NOT EXISTS lg_vector_document (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      VARCHAR(64) NOT NULL,
    version_id      VARCHAR(64) NOT NULL,
    chunk_type      VARCHAR(64) NOT NULL DEFAULT 'DOC',
    source_uri      TEXT,
    source_hash     VARCHAR(128),
    chunk_index     INT,
    content         TEXT NOT NULL,
    content_sha256  VARCHAR(128),
    meta            JSONB DEFAULT '{}'::JSONB,
    embedding       TEXT,
    embedding_model VARCHAR(128),
    embedding_dim   INT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_vector_doc_project_version
    ON lg_vector_document(project_id, version_id);

CREATE INDEX IF NOT EXISTS idx_vector_doc_chunk_type
    ON lg_vector_document(chunk_type);

-- 尝试将 embedding 列转为 pgvector 类型（扩展不可用时保持 TEXT）
DO $$
BEGIN
    ALTER TABLE lg_vector_document ALTER COLUMN embedding TYPE vector(1024) USING embedding::vector(1024);
    -- HNSW 索引
    CREATE INDEX IF NOT EXISTS idx_vector_doc_embedding
        ON lg_vector_document USING hnsw (embedding vector_cosine_ops);
    RAISE NOTICE 'pgvector embedding 列及 HNSW 索引创建成功';
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'pgvector 扩展未安装，embedding 列保持 TEXT 类型: %', SQLERRM;
END $$;

COMMENT ON TABLE lg_vector_document IS '向量文档表 — 代码/文档分片的 embedding 向量';
COMMENT ON COLUMN lg_vector_document.project_id IS '项目ID（UUID字符串）';
COMMENT ON COLUMN lg_vector_document.version_id IS '扫描版本ID';
COMMENT ON COLUMN lg_vector_document.chunk_type IS '分片类型：DOC/CODE/DB/UI';
COMMENT ON COLUMN lg_vector_document.embedding IS 'pgvector embedding 向量（或 TEXT 降级）';
