-- ============================================
-- V5: 补建缺失的图谱表 + 向量文档表（H2 已有，PG 遗漏）
-- ============================================

-- 1. 图谱节点表
CREATE TABLE IF NOT EXISTS lg_graph_node (
    id              UUID PRIMARY KEY,
    project_id      UUID NOT NULL REFERENCES lg_project(id),
    version_id      UUID NOT NULL REFERENCES lg_scan_version(id),
    node_type       VARCHAR(128) NOT NULL,
    node_key        VARCHAR(1024) NOT NULL,
    node_name       VARCHAR(512) NOT NULL,
    display_name    VARCHAR(512),
    description     TEXT,
    source_type     VARCHAR(64),
    source_path     TEXT,
    start_line      INT,
    end_line        INT,
    confidence      DECIMAL(5,4) NOT NULL DEFAULT 1.0000,
    status          VARCHAR(32) NOT NULL DEFAULT 'PENDING_CONFIRM',
    properties      TEXT,
    alias_names     TEXT,
    evidence_ids    TEXT,
    semantic_vector_ref BIGINT,
    verified_score  DECIMAL(5,4) DEFAULT 0.0000,
    runtime_verified BOOLEAN DEFAULT FALSE,
    last_seen_at    TIMESTAMP,
    trace_count     INT DEFAULT 0,
    deleted         SMALLINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, version_id, node_type, node_key)
);

CREATE INDEX IF NOT EXISTS idx_lg_graph_node_project_version ON lg_graph_node(project_id, version_id);
CREATE INDEX IF NOT EXISTS idx_lg_graph_node_type ON lg_graph_node(node_type);

-- 2. 图谱关系表
CREATE TABLE IF NOT EXISTS lg_graph_edge (
    id              UUID PRIMARY KEY,
    project_id      UUID NOT NULL REFERENCES lg_project(id),
    version_id      UUID NOT NULL REFERENCES lg_scan_version(id),
    from_node_id    UUID NOT NULL REFERENCES lg_graph_node(id),
    to_node_id      UUID NOT NULL REFERENCES lg_graph_node(id),
    edge_type       VARCHAR(128) NOT NULL,
    edge_key        VARCHAR(1024) NOT NULL,
    source_type     VARCHAR(64),
    confidence      DECIMAL(5,4) NOT NULL DEFAULT 1.0000,
    status          VARCHAR(32) NOT NULL DEFAULT 'PENDING_CONFIRM',
    properties      TEXT,
    deleted         SMALLINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, version_id, edge_key)
);

CREATE INDEX IF NOT EXISTS idx_lg_graph_edge_from ON lg_graph_edge(from_node_id);
CREATE INDEX IF NOT EXISTS idx_lg_graph_edge_to ON lg_graph_edge(to_node_id);
CREATE INDEX IF NOT EXISTS idx_lg_graph_edge_type ON lg_graph_edge(edge_type);

-- 3. 向量文档表（与 VectorDocument 实体对齐的 lg_ 前缀版本）
CREATE TABLE IF NOT EXISTS lg_vector_document (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT,
    chunk_type      VARCHAR(64),
    source_uri      TEXT,
    source_hash     VARCHAR(128),
    chunk_index     INT,
    content         TEXT NOT NULL,
    content_sha256  VARCHAR(128),
    meta            TEXT,
    embedding_model VARCHAR(128),
    embedding_dim   INT,
    deleted         SMALLINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE lg_graph_node IS '图谱节点表（与 Neo4j 同步）';
COMMENT ON TABLE lg_graph_edge IS '图谱关系表（与 Neo4j 同步）';
COMMENT ON TABLE lg_vector_document IS '向量文档表（pgvector 代码/文档分片向量）';
